# Generated by Django 5.0.4 on 2025-01-17 05:44

import django.core.validators
import profiles.imageUID
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profileicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileIcon',
            field=models.ImageField(default='profileIcon.png', upload_to=profiles.imageUID.profileIconUID, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
