# Generated by Django 5.0.4 on 2025-06-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('plants', '0011_lifecycle_lightrequirement_plant_soiltype'),
        ('profiles', '0006_profile_guestmode_alter_profile_displaytheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='climate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userClimate', to='home.city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='plantHistory',
            field=models.ManyToManyField(blank=True, related_name='plantUserHistory', to='home.plantsearchhistory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='plantInterests',
            field=models.ManyToManyField(blank=True, related_name='plantUserInterests', to='plants.plant'),
        ),
    ]
