# Generated by Django 5.0.4 on 2024-11-04 10:52

import django.core.validators
import profiles.imageUID
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_groupmessage_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profileIcon',
            field=models.ImageField(default='profileIcon.png', upload_to=profiles.imageUID.profileIconUID, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
