# Generated by Django 5.0.4 on 2024-11-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_group_profileicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='profileIcon',
            new_name='groupIcon',
        ),
    ]
