# Generated by Django 5.0.4 on 2024-11-14 11:18

import django.core.validators
import forum.imageUID
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_profileicon_group_groupicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupIcon',
            field=models.ImageField(default='profileIcon.png', upload_to=forum.imageUID.groupIconUID, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
