# Generated by Django 5.0.4 on 2024-11-15 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_group_groupicon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='deletedBy',
            field=models.ManyToManyField(blank=True, related_name='userDeletedGroupMessage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='deletedBy',
            field=models.ManyToManyField(blank=True, related_name='userDeletedMessage', to=settings.AUTH_USER_MODEL),
        ),
    ]
