# Generated by Django 5.0.4 on 2024-11-16 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_groupmessage_deletedby_message_deletedby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='request',
            field=models.ManyToManyField(related_name='groupRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
