# Generated by Django 5.0.4 on 2024-11-16 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_group_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='groupRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
