# Generated by Django 5.0.4 on 2024-12-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default="An empty canvas for your group's identity—add a description to set the tone!.", null=True),
        ),
    ]
