# Generated by Django 5.0.4 on 2025-01-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='isTask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='isTask',
            field=models.BooleanField(default=False),
        ),
    ]
