# Generated by Django 5.0.4 on 2025-01-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_group_istask_message_istask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='isTask',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='isTask',
            field=models.BooleanField(default=False),
        ),
    ]
