# Generated by Django 5.0.4 on 2025-01-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_remove_group_istask_groupmessage_istask'),
        ('tasks', '0006_tasks_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='isTask',
        ),
        migrations.RemoveField(
            model_name='message',
            name='isTask',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupMessageTask', to='tasks.tasks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='task',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='messageTask', to='tasks.tasks'),
            preserve_default=False,
        ),
    ]
