# Generated by Django 5.0.4 on 2025-01-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_remove_groupmessage_istask_remove_message_istask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='task',
        ),
        migrations.RemoveField(
            model_name='message',
            name='task',
        ),
    ]
