# Generated by Django 5.0.4 on 2025-01-06 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_remove_groupmessage_task_remove_message_task'),
        ('tasks', '0006_tasks_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupMessageTask', to='tasks.tasks'),
        ),
        migrations.AddField(
            model_name='message',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageTask', to='tasks.tasks'),
        ),
    ]
