# Generated by Django 5.0.4 on 2025-01-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_groupmessage_plant_message_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='autoJoin',
            field=models.BooleanField(default=True),
        ),
    ]
