# Generated by Django 5.0.4 on 2025-06-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_group_autojoin'),
        ('plants', '0011_lifecycle_lightrequirement_plant_soiltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupMessagePlant', to='plants.plant'),
        ),
        migrations.AlterField(
            model_name='message',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagePlants', to='plants.plant'),
        ),
    ]
