# Generated by Django 5.0.4 on 2024-11-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_remove_plants_task'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='plant',
            field=models.ManyToManyField(blank=True, related_name='taskPlant', to='plants.plants'),
        ),
    ]
