# Generated by Django 5.0.4 on 2024-11-16 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_remove_plants_task'),
        ('tasks', '0002_tasks_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='plant',
        ),
        migrations.AddField(
            model_name='tasks',
            name='plant',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taskPlant', to='plants.plants'),
            preserve_default=False,
        ),
    ]
