# Generated by Django 5.0.4 on 2024-11-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_remove_plants_task'),
        ('tasks', '0003_remove_tasks_plant_tasks_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskType', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskSuggestionsPlant', to='plants.plants')),
            ],
        ),
    ]
