# Generated by Django 5.0.4 on 2025-01-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
