# Generated by Django 5.0.4 on 2025-01-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='plant',
        ),
    ]
