# Generated by Django 5.0.4 on 2025-01-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_tasks_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='recurringType',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
    ]
