# Generated by Django 5.0.4 on 2025-06-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_tasks_recurringtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskSuggestion',
        ),
    ]
