# Generated by Django 5.0.4 on 2024-10-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plants',
            table=None,
        ),
    ]
