# Generated by Django 5.0.4 on 2024-11-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plants_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='binomialName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
