# Generated by Django 5.0.4 on 2024-11-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plants_binomialname'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='plantname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
