# Generated by Django 5.0.4 on 2024-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plants_plantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='sunRequirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
