# Generated by Django 5.0.4 on 2024-11-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plants_sunrequirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='plantname',
            new_name='plantName',
        ),
    ]
