# Generated by Django 5.0.4 on 2024-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_plants_task'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='task',
        ),
        migrations.AddField(
            model_name='plants',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='plantTask', to='tasks.tasks'),
        ),
    ]
