# Generated by Django 5.0.4 on 2024-11-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_remove_plants_task_plants_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='task',
        ),
    ]
