# Generated by Django 5.0.4 on 2025-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_groupmessage_plant_alter_message_plant'),
        ('plants', '0011_lifecycle_lightrequirement_plant_soiltype'),
        ('tasks', '0009_delete_tasksuggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plants',
        ),
        migrations.AddField(
            model_name='plant',
            name='lifeCycles',
            field=models.ManyToManyField(to='plants.lifecycle'),
        ),
        migrations.AddField(
            model_name='plant',
            name='lightRequirements',
            field=models.ManyToManyField(to='plants.lightrequirement'),
        ),
        migrations.AddField(
            model_name='plant',
            name='soilTypes',
            field=models.ManyToManyField(to='plants.soiltype'),
        ),
    ]
